### ISSUE TITLE
setup mongo db

### ISSUE THREAD

**Issue by futbotism** [hueSoft/hueCRM#11]
Hi, awesome lib for a starter. thanks for making it. Im wondering if you could elaborate on

> So you need to setup MongoDB and set the values for user collection according to the ./libs/schemas/src/lib/user.schema.ts

Im running mongo inside a docker container which seems to be connect to the api, but to i need to initialise the mongo instance with some sort of schema? When I create a user i just get 500

**Comment by Pietrox** [comment]
Hello, thanks for the compliment ;)

Did you try running "ng serve api" and use swagger under http://localhost:3000/api/docs/ ? Or any other port that you set up in .env?

In general i wrote it in code first apporach, so as long as NestJS has a module that is initializing a schema, it should create a ready to use but empty collection. That is why swagger comes in handy.

**Comment by futbotism** [comment]
Hey sorry about the late response the problem was with my docker set up, but thanks
